spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## service1
        - id: equipe
          uri: lb://equipe
          predicates:
            - Path=/equipe/**
          filters:
            - StripPrefix=1

        ## Service2
        - id: usermicroservice
          uri: lb://usermicroservice
          predicates:
            - Path=/usermicroservice/**
          filters:
            - StripPrefix=1
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka